### ISSUE TITLE
Heap-buffer-overflow in wvtest with ASAN

### ISSUE THREAD

**Issue by Yhcrown** [dbry/WavPack#127]
Hi, developers of WavPack:
Recently, I test the binary **wvtest** instrumented with ASAN. Unfortunately, it incurred a crash with the following error information. Any help would be greatly appreciated from you :D

```
=================================================================
==124665==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x620000000ec0 at pc 0x55a70e5e6000 bp 0x7ffd5b40a850 sp 0x7ffd5b40a848
WRITE of size 1 at 0x620000000ec0 thread T0
    #0 0x55a70e5e5fff in MD5_Final /workspace/WavPack/cli/md5.c:283:2
    #1 0x55a70e5d170e in seeking_test /workspace/WavPack/cli/wvtest.c:360:13
    #2 0x55a70e5d170e in main /workspace/WavPack/cli/wvtest.c:250:24
    #3 0x7f17e6a80d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)
    #4 0x7f17e6a80e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)
    #5 0x55a70e5125a4 in _start (/workspace/WavPack/check_build/wvtest+0x265a4) (BuildId: d2bb1b0d0f02406e87d65aef508aa01854709b15)

0x620000000ec0 is located 0 bytes to the right of 3648-byte region [0x620000000080,0x620000000ec0)
allocated by thread T0 here:
    #0 0x55a70e5953ee in __interceptor_malloc (/workspace/WavPack/check_build/wvtest+0xa93ee) (BuildId: d2bb1b0d0f02406e87d65aef508aa01854709b15)
    #1 0x55a70e5d1633 in seeking_test /workspace/WavPack/cli/wvtest.c:337:23
    #2 0x55a70e5d1633 in main /workspace/WavPack/cli/wvtest.c:250:24
    #3 0x7f17e6a80d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)

SUMMARY: AddressSanitizer: heap-buffer-overflow /workspace/WavPack/cli/md5.c:283:2 in MD5_Final
Shadow bytes around the buggy address:
  0x0c407fff8180: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c407fff8190: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c407fff81a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c407fff81b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c407fff81c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c407fff81d0: 00 00 00 00 00 00 00 00[fa]fa fa fa fa fa fa fa
  0x0c407fff81e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c407fff81f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c407fff8200: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c407fff8210: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c407fff8220: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==124665==ABORTING
```
### Crash input:
https://github.com/Yhcrown/fuzzing-crashes/blob/main/validated/wvtest/0

### Verification steps：

```
git clone https://github.com/dbry/WavPack
cd WavPack/
mkdir check_build && cd check_build
cmake ../ -DCMAKE_C_COMPILER=clang  -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_FLAGS="-fsanitize=address" -DCMAKE_CXX_FLAGS="-fsanitize=address"
make -j 
./wvtest --seektest ./crash_input
```
enviroment:
Ubuntu 22.04 LTS
Linux lab-pro 4.15.0-147-generic
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Ubuntu clang version 14.0.6

**Thanks & Best regards !**

**Comment by dbry** [comment]
Hi, and thanks for reporting this!

The problem was that the `seektest` expects a valid WavPack file, not the output of a fuzzer. It's purpose is to test the seeking function of `libwavpack` with varying, but valid, files. In this case the WavPack file was longer than its header indicated, which we were not checking for when reading the file. I have pushed a fix for this, but there could certainly be other bugs in the tester, not to mention memory leaks.

Since `wvtest` is not a user-facing program, or even available in any distribution, I do not consider this a security issue. And I also believe that even if a bug _was_ found in the `libwavpack` seeking code, it would not be a great security risk either because of the difficulty of triggering it outside of the lab.

**Comment by Yhcrown** [comment]
As you have analyzed, this is a small bug rather than a security vulnerability. Thank you very much for fixing it.
