### ISSUE TITLE
SEGV in get_words_lossless() when doing WavpackUnpackSamples()

### ISSUE THREAD

**Issue by stolk** [dbry/WavPack#25]
I'm reading a wv file, generated with wavpack on Ubuntu, as follows:

```
        char error[80];
        WavpackContext *ctx = WavpackOpenFileInput
        (
                "./Sound/sarabande.wv",
                error,
                OPEN_WVC,
                0
        );
        if ( !ctx )
        {
                LOGE( "WavpackOpenFileInput failed: %s", error );
        }
        else
        {
                const int bps = WavpackGetBytesPerSample( ctx );
                const uint32_t nsam = WavpackGetNumSamples( ctx );
                const int nchan = WavpackGetNumChannels( ctx );
                uint32_t sz = nchan * nsam * bps;
                LOGI( "number of channels: %d, bytes per sample: %d, numsamples: %d", nchan, bps, nsam );
                musi = (short*) malloc( sz );
                ASSERT( musi );
                uint32_t rv = WavpackUnpackSamples( ctx, (int32_t*) musi, nsam*nchan );
```

Which gives a SEGV in:

```
Thread 1 "blox" received signal SIGSEGV, Segmentation fault.
get_words_lossless (wps=wps@entry=0x107a7a80, buffer=buffer@entry=0x7fffee06f4b0, nsamples=88200, nsamples@entry=44100) at read_words.c:353
353	            buffer [csamples] = (getbit (bs)) ? ~low : low;
(gdb) where
#0  get_words_lossless (wps=wps@entry=0x107a7a80, buffer=buffer@entry=0x7fffee06f4b0, nsamples=88200, nsamples@entry=44100) at read_words.c:353
#1  0x0000000000438ed2 in unpack_samples (wpc=wpc@entry=0x107a7800, buffer=buffer@entry=0x7fffee06f4b0, sample_count=sample_count@entry=44100) at unpack.c:174
#2  0x00000000004332e3 in WavpackUnpackSamples (wpc=0x107a7800, buffer=0x7fffec3d6010, samples=11333570) at unpack_utils.c:356
```

My output:
```
number of channels: 2, bytes per sample: 2, numsamples: 7541035
```

My file:
```
$ wvunpack -s Sound/sarabande.wv 

 WVUNPACK  Hybrid Lossless Audio Decompressor  Linux Version 5.1.0
 Copyright (c) 1998 - 2017 David Bryant.  All Rights Reserved.


file name:         Sound/sarabande.wv
file size:         14230764 bytes
source:            16-bit ints at 44100 Hz
channels:          2 (stereo)
duration:          0:02:51.00
modalities:        lossless, high
compression:       52.82%
ave bitrate:       666 kbps
encoder version:   4
```

**Comment by stolk** [comment]
It looks like 16 bit values are actually unpacked as 32bit ints?

Doesn't this waste a lot of memory when reading 16bit samples?

Is there a way to unpack them tightly packed as 2 shorts per frame?

**Comment by dbry** [comment]
Hi. I think I know what the problem is. ```WavpackUnpackSamples()``` _always_ returns the sample data in 32-bit words, even if ```WavpackGetBytesPerSample()``` returns something other than 4. If you look at the documentation for ```WavpackUnpackSamples()``` in the library documentation it should make more sense. In your case, the samples would be returned in the lower 2 bytes of each 4 byte word.

Hope this makes sense, and if you still have trouble please let me know.

-David

**Comment by dbry** [comment]
Sorry, I saw your second post after my reply. Unfortunately there is no way to unpack directly into 16-bit data. The reason behind this is that internally WavPack is always working with 32-bit samples, so there is only one version of all the various compression algorithms and functions. Even if I wanted to return packed data, I would still have to unpack to 32-bits internally and then copy it out, so there wouldn't actually be any memory or time savings.
